<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-02-05 03:04
=======
# Generated by Django 5.1.5 on 2025-02-04 07:34
>>>>>>> 69b829b170673d2c084e73dd4de6292ba4f2c6de

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('tourist', '관광지'), ('restaurant', '맛집'), ('cafe', '카페')], max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
=======
            name="Place",
>>>>>>> 69b829b170673d2c084e73dd4de6292ba4f2c6de
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tourist", "관광지"),
                            ("restaurant", "맛집"),
                            ("cafe", "카페"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("review_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="YouTubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_id", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("captions", models.TextField(blank=True, null=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
